import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import AlertMessage from "@/components/alertMessage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <StoreProvider>
                <body className={inter.className}>
                    {children}
                    {<AlertMessage />}
                </body>
            </StoreProvider>
        </html>
    );
}

export default RootLayout;
